import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import React from 'react'
import { getCoins } from './api/hello'
import Button from 'antd/lib/button'
import Input from 'antd/lib/input'
import Card from 'antd/lib/card'
import Space from 'antd/lib/space'
import Typography from 'antd/lib/typography'
import Divider from 'antd/lib/divider'
import Title from 'antd/lib/typography/Title'

export default function Home() {
	const [onChainAddress, setOnChainAddress] = React.useState('')
	return (
		<div className={styles.container}>
			<Head>
				<title>Plebnet.fun</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main className={styles.main}>
				<Title>
					{' '}
					Welcome to the <a>Plebnet.fun</a> faucet
				</Title>

				<div style={{ marginBottom: 48 }}>
					<Image
						src='/playgroundCropped.png'
						alt='Vercel Logo'
						width={703 / 1.5}
						height={377 / 1.5}
					/>
				</div>

				<Title level={4}>Get test coins here:</Title>
				{/* <p className={styles.description}>Get test coins here:</p> */}
				<div style={{ display: 'flex', width: '80%' }}>
					<Input
						value={onChainAddress}
						onChange={(e) => setOnChainAddress(e.target.value)}
						placeholder='Enter your on-chain address'
					/>

					<Button
						loading={false}
						style={{ marginLeft: 8 }}
						onClick={() => getCoins(onChainAddress)}
						type='primary'>
						Submit
					</Button>
				</div>

				{/* <Divider /> */}

				{/* <Card
						size='small'
						title='Small size card'
						extra={<a href='#'>More</a>}
						style={{ width: 300 }}>
						<p>Card content</p>
						<p>Card content</p>
						<p>Card content</p>
					</Card>

					<a
						href='https://plebnet.wiki/wiki/Plebnet_Playground'
						className={styles.card}>
						<h2>Wiki Page &rarr;</h2>
						<p>Find in-depth information about the Plebnet Playground</p>
					</a>

					<a
						href='https://github.com/PLEBNET-PLAYGROUND'
						className={styles.card}>
						<h2>GitHub &rarr;</h2>
						<p>All of the Plebnet Playground code in one place!</p>
					</a>

					<a
						href='https://github.com/PLEBNET-PLAYGROUND/plebnet-playground-docker#readme'
						className={styles.card}>
						<h2>Learn More &rarr;</h2>
						<p>An in depth explanation of plebnet</p>
					</a> */}

				{/* <a
						href='https://github.com/vercel/next.js/tree/master/examples'
						className={styles.card}>
						<h2>Examples &rarr;</h2>
						<p>Discover and deploy boilerplate example Next.js projects.</p>
					</a>

					<a
						href='https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
						className={styles.card}>
						<h2>Deploy &rarr;</h2>
						<p>
							Instantly deploy your Next.js site to a public URL with Vercel.
						</p>
					</a> */}
			</main>

			<footer className={styles.footer}>
				<Space split={<Divider type='vertical' />}>
					<Typography.Link href='https://plebnet.wiki/wiki/Plebnet_Playground'>
						Wiki Page
					</Typography.Link>
					<Typography.Link href='https://github.com/PLEBNET-PLAYGROUND'>
						GitHub
					</Typography.Link>
					<Typography.Link href='https://github.com/PLEBNET-PLAYGROUND/plebnet-playground-docker#readme'>
						More Info
					</Typography.Link>
				</Space>

				{/* // <a
				// 	href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
				// 	target='_blank'
				// 	rel='noopener noreferrer'>
				// 	Powered by{' '}
				// 	<span className={styles.logo}>
				// 		<Image src='/vercel.svg' alt='Vercel Logo' width={72} height={16} />
				// 	</span>
				// </a> */}
			</footer>
		</div>
	)
}
